### ISSUE TITLE
python3: no such file or directory (on macOS)

### ISSUE THREAD

**Issue by mchowX** [mackorone/mms-python#1]
![screen shot 2019-02-05 at 1 48 30 pm](https://user-images.githubusercontent.com/72857/52296627-da67cd80-294c-11e9-812d-7a68409ad4f9.png)

**Comment by mchowX** [comment]
python3 is installed

**Comment by jrhoeber** [comment]
+1 this issue. Running on macOS Mojave 10.14 with Python 3.7.2. C++ algo files work fine.

**Comment by mackorone** [comment]
Thanks for letting me know! The first issue was that Python 3 isn't installed by default on macOS. Thus, we're forced to use Python 2. Additionally, I also had to add some logic to flush stdout after each command. Here's the fix: 78eaf6cbafcc222bf25c3a42824fc56ccc48c830
